command displays error message if user tries to delete recycle file

diff --git a/recycle b/recycle
--- a/recycle
+++ b/recycle
@@ -1,4 +1,3 @@
-
 #check for correct number of arguments
 
 if [ $# -eq 0 ] #give missing operand warning for no arguments
@@ -12,12 +11,18 @@ then
         then
                 if [ -d $1 ] #is it a directory?
                 then
-                                echo "recycle: cannot remove '$1': Is a directory"
+                        echo "recycle: cannot remove '$1': Is a directory"
+                        exit 1
+                else
+                        if [ $1 = "recycle" ]
+                        then
+                                echo "Attempting to delete recycle - operation aborted"
                                 exit 1
                         else
                                 echo "it is a proper file"
+                                exit 0
+                        fi
                 fi
-                exit 0
         else
                 echo "recycle: cannot remove '$1': No such file or directory"
                 exit 1
